import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "on-secondary": "#412d00",
        "secondary": "#e9c176",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#e3e2e0",
        "surface": "#131313",
        "on-primary-fixed-variant": "#574500",
        "outline-variant": "#4d4635",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#393939",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "primary-container": "#d4af37",
        "error-container": "#93000a",
        "tertiary-container": "#b3b3b1",
        "surface-tint": "#e9c349",
        "secondary-fixed": "#ffdea5",
        "on-tertiary-fixed": "#1b1c1b",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "on-secondary-fixed-variant": "#5d4201",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#ffe088",
        "on-secondary-container": "#dab36a",
        "inverse-primary": "#735c00",
        "secondary-fixed-dim": "#e9c176",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed-dim": "#c7c6c4",
        "on-tertiary-fixed-variant": "#464746",
        "on-tertiary": "#303130",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-background": "#e5e2e1",
        "outline": "#99907c",
        "tertiary": "#cfcecc",
        "on-primary-fixed": "#241a00",
        "primary-fixed-dim": "#e9c349",
        "on-tertiary-container": "#444544",
        "secondary-container": "#604403",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#d0c5af",
        "primary": "#f2ca50",
        "on-primary": "#3c2f00",
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#261900",
        "surface-variant": "#353534",
        "on-primary-container": "#554300",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
